#!/usr/bin/env python3
"""Generate engine/quanpin/autocorrect_table.h from quanpin_utils.cpp.

The intact pinyin list is parsed directly from the engine source, so the
generated table can never drift from the runtime syllable list.

The table is split in two so each autocorrection type can be toggled
independently (quanpin.autocorrect_transposition / autocorrect_neighbor,
both default off):
  - transposition: single adjacent-letter swap, sahng -> shang
  - neighbor:      single QWERTY neighbor-key substitution, shabg -> shang

Variant length is capped at >= 3: every 2-letter string belongs to the
jianpin (abbreviated pinyin) space, where "wj" means w+j and must never be
rewritten into "wu" by the correction table.

Usage:
    python scripts/generate_quanpin_autocorrect.py          # regenerate the header
    python scripts/generate_quanpin_autocorrect.py --check  # verify the header is up to date (CI)
"""

from __future__ import annotations

import pathlib
import re
import sys

ENGINE_DIR = pathlib.Path(__file__).resolve().parents[2] / "engine"
UTILS_PATH = ENGINE_DIR / "quanpin" / "quanpin_utils.cpp"
OUT_PATH = ENGINE_DIR / "quanpin" / "autocorrect_table.h"

# QWERTY letter-key neighbors (finger-movement range, letter keys only).
QWERTY_NEIGHBORS = {
    "q": ["w", "a"],
    "w": ["q", "e", "s", "a"],
    "e": ["w", "r", "s", "d"],
    "r": ["e", "t", "d", "f"],
    "t": ["r", "y", "f", "g"],
    "y": ["t", "u", "g", "h"],
    "u": ["y", "i", "h", "j"],
    "i": ["u", "o", "j", "k"],
    "o": ["i", "p", "k", "l"],
    "p": ["o", "l"],
    "a": ["q", "w", "s", "z"],
    "s": ["a", "w", "d", "e", "x", "z"],
    "d": ["s", "e", "r", "f", "c", "x"],
    "f": ["d", "r", "t", "g", "v", "c"],
    "g": ["f", "t", "y", "h", "b", "v"],
    "h": ["g", "y", "u", "j", "n", "b"],
    "j": ["h", "u", "i", "k", "m", "n"],
    "k": ["j", "i", "o", "l", "m"],
    "l": ["k", "o", "p"],
    "z": ["a", "s", "x"],
    "x": ["z", "s", "d", "c"],
    "c": ["x", "d", "f", "v"],
    "v": ["c", "f", "g", "b"],
    "b": ["v", "g", "h", "n"],
    "m": ["n", "j", "k"],
    "n": ["b", "h", "j", "m"],
}

HEADER_TEMPLATE = """\
// Generated by scripts/generate_quanpin_autocorrect.py -- DO NOT EDIT.
// Quanpin typing autocorrection tables: wrong spelling -> correct syllable.
// Rules: single adjacent-letter transposition, or single neighbor-key
// substitution on a QWERTY layout, applied to one legal syllable.
// Every key is a non-legal pinyin string of at least three letters (2-letter
// strings belong to the jianpin space) and maps to exactly one syllable.
// The two tables back the independently toggleable correction types.
#pragma once

#include <cstddef>

namespace quanpin::autocorrect
{{
struct Entry
{{
    const char *wrong;
    const char *correct;
}};

// Adjacent-letter transpositions: sahng -> shang.
inline constexpr Entry kTranspositionEntries[] = {{
{transposition_entries}
}};

// QWERTY neighbor-key substitutions: shabg -> shang (n -> b).
inline constexpr Entry kNeighborEntries[] = {{
{neighbor_entries}
}};

inline constexpr std::size_t kTranspositionCount = sizeof(kTranspositionEntries) / sizeof(kTranspositionEntries[0]);
inline constexpr std::size_t kNeighborCount = sizeof(kNeighborEntries) / sizeof(kNeighborEntries[0]);

}} // namespace quanpin::autocorrect
"""


def extract_intact_pinyin_list() -> list[str]:
    text = UTILS_PATH.read_text(encoding="utf-8")
    match = re.search(r"intact_pinyin_list\(\)[\s\S]*?kList = \{([\s\S]*?)\};", text)
    if not match:
        raise SystemExit("ERROR: cannot find intact_pinyin_list in " + str(UTILS_PATH))
    return re.findall(r'"([a-z]+)"', match.group(1))


def build_variants(
    syllables: list[str], make_variants, min_length: int
) -> dict[str, str]:
    """Run one rule path over all syllables, dropping ambiguous variants.

    A wrong string that would map to two different syllables is dropped
    entirely so the runtime never guesses.
    """
    valid = set(syllables)
    mapping: dict[str, str] = {}

    def add_variant(variant: str, correct: str) -> None:
        if (
            variant == correct
            or variant in valid
            or len(variant) < min_length
            or len(variant) > 6
            or "'" in variant
        ):
            return
        existing = mapping.get(variant)
        if existing is None:
            mapping[variant] = correct
        elif existing != correct:
            del mapping[variant]

    for syllable in syllables:
        if len(syllable) < 2:
            continue
        for variant in make_variants(syllable):
            add_variant(variant, syllable)

    return mapping


def build_entries(syllables: list[str]) -> tuple[dict[str, str], dict[str, str]]:
    def transposition_variants(syllable: str):
        # sahng -> shang: swap each adjacent letter pair.
        return (
            syllable[:i] + syllable[i + 1] + syllable[i] + syllable[i + 2 :]
            for i in range(len(syllable) - 1)
        )

    def neighbor_variants(syllable: str):
        # shabg -> shang: replace each letter with a QWERTY neighbor.
        return (
            syllable[:i] + neighbor + syllable[i + 1 :]
            for i, ch in enumerate(syllable)
            for neighbor in QWERTY_NEIGHBORS.get(ch, ())
        )

    # 2-letter strings are jianpin space (wj/wh/wk/wl...), never correction keys.
    transposition = build_variants(syllables, transposition_variants, min_length=3)
    neighbor = build_variants(syllables, neighbor_variants, min_length=3)

    # Cross-type conflicts: the same wrong string produced by both rules.
    # Different corrections -> ambiguous, drop everywhere; same correction ->
    # keep it in the neighbor table only (the weaker-cost rule).
    for wrong in sorted(set(transposition) & set(neighbor)):
        if transposition[wrong] != neighbor[wrong]:
            del transposition[wrong]
            del neighbor[wrong]
        else:
            del transposition[wrong]

    return transposition, neighbor


def render_entry_lines(entries: dict[str, str]) -> str:
    """Compact layout: 5 entries per line in fixed-width 22-char cells."""
    cells = [f'{{"{wrong}", "{correct}"}},' for wrong, correct in sorted(entries.items())]
    lines = []
    for i in range(0, len(cells), 5):
        lines.append("    " + "".join(cell.ljust(22) for cell in cells[i : i + 5]).rstrip())
    return "\n".join(lines)


def render_header(transposition: dict[str, str], neighbor: dict[str, str]) -> str:
    return HEADER_TEMPLATE.format(
        transposition_entries=render_entry_lines(transposition),
        neighbor_entries=render_entry_lines(neighbor),
    )


def main() -> int:
    syllables = extract_intact_pinyin_list()
    if not syllables:
        raise SystemExit("ERROR: extracted empty pinyin list")
    transposition, neighbor = build_entries(syllables)
    rendered = render_header(transposition, neighbor)

    if "--check" in sys.argv[1:]:
        if not OUT_PATH.exists():
            raise SystemExit(f"ERROR: {OUT_PATH} is missing")
        if OUT_PATH.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"ERROR: {OUT_PATH} is stale; rerun generate_quanpin_autocorrect.py")
        print(f"OK: {OUT_PATH} is up to date "
              f"({len(transposition)} transposition + {len(neighbor)} neighbor entries)")
        return 0

    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUT_PATH} with {len(transposition)} transposition + {len(neighbor)} neighbor "
          f"entries (from {len(syllables)} legal syllables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
